export const enum StatutAffaire {
  DRAFT = 'DRAFT',

  PREPARATION_OFFRE_TECHNIQUE = 'PREPARATION_OFFRE_TECHNIQUE',

  PREPARATION_OFFRE_ADMINISTRATIVE = 'PREPARATION_OFFRE_ADMINISTRATIVE',

  OFFRE_FOURNISSEUR = 'OFFRE_FOURNISSEUR',

  SOUMISSION = 'SOUMISSION',

  EXECUTION = 'EXECUTION',

  CLOTUREE = 'CLOTUREE',
}
